# Systematic review

## Systematic searching

### Developing search terms 

Developing optimal search terms to identify all potentially relevant studies is a hugely important step in your systematic review. A few resources to help you with this process are highlighted below: 

- [Step-by-step guide](https://journals.sagepub.com/doi/full/10.1258/la.2011.011087)for identifying preclinical animal studies from our collaborators, SyRCLE

- This [useful resource](https://utas.libguides.com/SystematicReviews/SearchStrategies#:~:text=%20These%20are%20the%20steps%20required%20when%20developing,different%20databases%2011%20Final%20search%20strategy%20More%20) from the University of Tasmania 

### Downloading references to Endnote

Endnote is our citation manager of choice within the team. It is fairly user-friendly, has lots of export formats, and can be used to find PDFs for citations. If you are a student at the university, you can request to download Endnote [here](https://www.ed.ac.uk/information-services/computing/desktop-personal/software/main-software-deals/endnote) 

#### Pubmed 

Use the Advanced Search builder on [Pubmed](https://www.ncbi.nlm.nih.gov/pubmed/) to search for relevant records. Click *Send to* and *citation manager* to import into Endnote directly.  

Troubleshooting: 
If you have >10,000 records, you will have to do this multiple times. If this is the case, you can filter by year of publication by going to the PUBLICATION DATE filters on the right hand side and selecting *Custom range*. The publications over time bar plot on the right hand side should not be used for filtering - in our experience this has a lot of overlapping publications across years and the results do not total up correctly. 

In some cases, with very large numbers of records Endnote may crash during the download. If this happens, filter by Year in PubMed to split the records into smaller file sizes (e.g. 5,000 records) and import each one separately.

#### Web of Science

Log in to WOS [here](https://www.ed.ac.uk/information-services/help-consultancy/archive-for-usd-container/web-of-science)

To export up to 500 records at a time, select *Export* and *Endnote desktop*. Alternatively, the option may be available to you via your institution to download 5000 references at a time. If possible, select this option and download to a tab deliminted format. Once downloaded, you will need to import into excel to perform some data cleaning and formatting. In excel, select *Data* and *From text* to import the .txt file. The column headers must be changed to the following:

- PT - Reference Type
- AU - Author
- TI - Title
- SO - Secondary Title
- UT - Accession Number
- PD - Date
- PY - Year
- VL - Volume
- IS - Number
- TC (citation count) - If you want to keep this or any others call them Custom 1, Custom 2.. etc. 

For pages, you need to create a new column in excel called *Pages*. Enter a foruma that will add the contents of the *BP* (beginning page) and *EP* (ending page) columns with a "-" in the middle e.g. *=E1&"-"&F1"* and paste down the column length. Once complete, copy paste this column and ensure it is pasted as the values, so you can delete the *BP* and *EP* columns. 

Finally, insert a row above the column names with **Generic* in cell *A1*. Save as a tab delimited text file. Open up in Notepad and remove any tabs after the **Generic* so that *Reference Type* begins on a new line but with no tabs in between. 

Now, go to Endnote and import the file by going to *File* -> *Import* -> *File* and selecting Import option *Tab Delimited*. Before improting, select *UTF-8* for text-translation, and *Import All duplicates*.

#### EMBASE

Log in to Embase [here](https://www.ed.ac.uk/information-services/help-consultancy/archive-for-usd-container/embase)

In the *Range* field, enter 1-5000 to download 5000 records at a time (or whichever limit your institution allows). *Do not* click *Go* and instead click *Export*. Export references in Endnote format and once downloaded, click the file to import into Endnote automatically. Alternatively, right click the file and select *Endnote* under the *Open with...* list. 

## Removing duplicates 

If you conduct a systematic search across multiple databases, you will need to remove duplicate records - e.g. the same record which has been identified in several databases. This is not a straightforward task, as the same record may differ slightly in title, authors, and other reference information due to the way it has been indexed in different databases. Endnote is a popular tool for duplicate removal, however there is evidence that it is not sufficient and misses many duplicates.

### ASySD 
The Automated Systematic Search Deduplicator [ASySD](https://camarades.shinyapps.io/RDedup/) was developed within CAMARADES to address this problem automatically remove duplicate references. First, export your records as an .XML file from Endnote and upload to ASySD. Next, move to the next "Deduplication" tab to remove duplicate records. There is also an option of completing manual deduplication (where the algorithm detects pairs of records which *might* be duplicates). Follow the instructions on the application to select the IDs of records you wish to remove from any pair and click to remove records from dataset when complete. On the final tab, you can download your unique systematic search dataset in multiple formats. We recommend downloading the Endnote tab delimited (.txt) file and importing to a new Endnote library. 

### Endnote 


## Screening for inclusion

## Extracting information

## Extracting numerical data

## Summarising your results

